# Generated by Django 5.0.7 on 2026-08-17 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('explain_code', 'Explain code'), ('find_bugs', 'Find bugs'), ('fix_bugs', 'Fix bugs'), ('optimize_code', 'Optimize code'), ('generate_code', 'Generate code'), ('convert_code', 'Convert code'), ('generate_comments', 'Generate comments'), ('generate_documentation', 'Generate documentation'), ('generate_tests', 'Generate test cases'), ('generate_sql', 'Generate SQL'), ('explain_error', 'Explain error message'), ('security_scan', 'Detect security issues'), ('quality_score', 'Code quality score'), ('complexity_analysis', 'Complexity analysis'), ('code_review', 'AI code review')], max_length=30)),
                ('language', models.CharField(blank=True, default='', max_length=20)),
                ('input_summary', models.CharField(blank=True, default='', max_length=255)),
                ('output', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], default='success', max_length=10)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('engine_used', models.CharField(default='heuristic', max_length=20)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectfile')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_requests', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ai_engine_a_user_id_a7e186_idx'), models.Index(fields=['feature'], name='ai_engine_a_feature_4cfc93_idx')],
            },
        ),
    ]
